name: Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2 # 현재 상태의 소스코드를 가상의 컨테이너 안으로 checkout
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: decrypt secret file
      run: ./decrypt-secret.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
        
    - name: Grant execute permission for gradlew 
      run: chmod +x gradlew 
    - name: Build with Gradle 
      run: ./gradlew build

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

#     - name: Build and push
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: hoit1302/efub:latest
        
    - name: build and push to DockerHub
      env:
        NAME: hoit1302
        REPO: efub
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
